management:
    endpoints:
        web:
            exposure:
                include: mappings
spring:
    application:
        name: BookStore

    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        cache: false

    datasource:
        url: jdbc:h2:mem:bookstore;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=true
        username: sa
        password:
        driverClassName: org.h2.Driver
        schema: classpath:schema.sql

    h2:
        console:
            enabled: true
            path: /h2-console
